openapi: 3.0.4
info:
  title: Human Name Parser
  description: Human Name Parser is a simple tool for parsing human names into their components. It returns the parsed components of the human name.
  termsOfService: https://apiverve.com/terms/
  contact:
    name: APIVerve Support
    email: hello@apiverve.com
    url: https://apiverve.com/contact
  version: 1.0.9
externalDocs:
  description: Learn more about APIVerve
  url: https://docs.apiverve.com?utm_source=openapi
servers:
- url: https://api.apiverve.com/
paths:
  /v1/humannameparser:
    get:
      summary: Parse Human Name
      description: Human Name Parser is a simple tool for parsing human names into their components. It returns the parsed components of the human name.
      operationId: humannameparser
      parameters:
      - name: name
        in: query
        schema:
          type: string
        required: true
        description: The human name to parse
        example: MR. MARTINO PETROS DE FLORENCE (TINO) Jr.
      responses:
        '200':
          description: Successful Response
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
                    description: status
                  error:
                    type: string
                    description: error
                  data:
                    type: string
                    description: data
              example:
                status: ok
                error: 
                data:
                  name: MR. MARTINO PETROS DE FLORENCE (TINO) Jr.
                  parsed:
                    title: Mr.
                    first: Martino
                    middle: Petros
                    last: de Florence
                    nick: Tino
                    suffix: Jr.
        '401':
          description: Your request was not authorized, or your API Key was invalid
        '404':
          description: Requested resource was not found
        '500':
          description: A server error has occured, try again later
components:
  securitySchemes:
    api_key:
      type: apiKey
      name: x-api-key
      in: header
security:
- api_key: []
